### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by goldorak135** [Magic-Bots/xenon#115]
Hello I took a capture from a server to put it on another server when I copy the message to put on the new server and I enter it the correct you answer me that you do not exist

**Comment by ThatLifeofGames** [comment]
This doesn't help diagnose a problem at all. 99% chance it can be solved in the support server rather than it just being declared as a "bug". This is most likely a user issue.

You can either make it clear that this is actually a bug by being more descriptive or i'll close the issue soon (and come and work it out in the support server).

**Comment by goldorak135** [comment]
I also think that it is a user error but I do not know how to put my backup on my new server would you have a solution or an explanation to detail

**Comment by merlinfuchs** [comment]
Please join the support server https://discord.club/discord and ask in the support channel.
This is not the right place for that type of problems.
